name: CI

on: 
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm i
      - run: CI=false npm run build
      - name: Build
        run: |
          git checkout --orphan develop-build
          rm .gitignore
          git reset
          git add build
          git remote set-url origin https://hdduy97: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@github.com/hdduy97/test123.git
          tail .git/config
          git status
          git config user.name "Duy Huynh"
          git config user.email "hdduy97@gmail.com"
          git commit -m "build"
          git push origin develop-build
