name: CI

on: 
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm i
      - run: CI=false npm run build
      - name: Build
        run: |
          rm .gitignore
          git add build
          git status
          git config user.name "Duy Huynh"
          git config user.email "hdduy97@gmail.com"
          git commit -m "build"
      - name: Push changes
        with:
          github_token: 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
          branch: develop-build
